version: 2
updates:
  - package-ecosystem: "npm"
    labels:
      - dependencies
    directory: "/"  # refers to the location of package.json
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
