# example
filters:
  - label: "👷🏻‍♂️ status: awaiting triage"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]
    
  - label: "duplicate"
    regexs:
      - /feat/i
    events: [pull_request]
    targets: [title]
